### ISSUE TITLE
DemoParser not parsing anything for some demos

### ISSUE THREAD

**Issue by AryanAb** [LaihoE/Python-demoparser#10]
Parsing demos that were recorded in game using the `record` command seems not to be working. The demo file in question is [here](https://drive.google.com/file/d/1UmaIQgMYXdBz__GmLU6xMPnslxhA0Brb/view?usp=sharing), and the code used to parse is as follows:

```python
from demoparser import DemoParser

demo_path = 'PATH_TO_DEMO/weapontest.dem'
parser = DemoParser(demo_path)
df = parser.parse_ticks(['weapon_name'])
print(df)
```

The output is simply an empty data-frame. The demo is not corrupted either, as I can open it in CS:GO and view it. This doesn't happen with demos downloaded from hltv.org.

Interestingly enough, the header information is parsed correctly using `parser.parse_header()`. But neither `parse_events` nor `parse_ticks` seem to work.

**Comment by LaihoE** [comment]
Yeah these are "POV" demos. Not sure what the difference is, and a quick scan trough the other parsers didn't make it any clearer. Let's revisit this in the source2 parser. Sorry, you'll just have to wait :disappointed:

**Comment by AryanAb** [comment]
No worries. This issue isn't anything major for me anyways, I just wanted to bring it to your attention.

Your tool is very helpful and thanks for everything. I'll be sure to check the source 2 version.
