### ISSUE TITLE
Round is not correctly detected

### ISSUE THREAD

**Issue by statist32** [LaihoE/Python-demoparser#12]
If I am parsing game events like 'weapon_fire' or 'player_death', the round property is always 0.
I guess that the round change is not propagated correctly.

**Comment by LaihoE** [comment]
Hi, yeah this is a bug that was never fixed as I moved on to the CS2 parser. There is a hack that can fix it:

```python
df = parser.parse_events("weapon_fire", props=["round"])
```
Adding props=["round"] should give you the correct round. Yes this is very nasty sorry.


Anyhow this has properly been fixed in CS2 version.

**Comment by statist32** [comment]
Thanks for the workaround.
Am I correct, that the cs2 parser can not parse csgo demos?

**Comment by LaihoE** [comment]
No, you will have to use this one for csgo demos.
