### ISSUE TITLE
Filter non-player from game events

### ISSUE THREAD

**Issue by LaihoE** [LaihoE/Python-demoparser#2]

**Comment by AryanAb** [comment]
This would be a useful feature to have. Currently the only reliable way of doing this for my use case is to manually filter spectators out of the final result.

**Comment by LaihoE** [comment]
Do you happen to have an example of this? Mostly interested in what type of events you are parsing.

**Comment by AryanAb** [comment]
I'm trying to get the information of all players when a kill happens. My code looks roughly like this:

```python
parser = DemoParser(demo_path)
death_event = parser.parse_events('player_death')
deaths = pd.DataFrame(death_event)

# get a list of ticks when a death occurred
all_death_ticks = deaths['tick'].tolist()

ticks_df = parser.parse_ticks(['X', 'Y', 'Z'], ticks=all_death_ticks)
ticks_df.to_csv(output_path, index=False)
```
This gives the information of the players but also the information the observers of the game. For instance, if I use [this game](https://www.hltv.org/matches/2360640/heroic-vs-natus-vincere-blast-premier-world-final-2022) not only I get the ten players, but also three observers: Linaaa, @shevcsgo, zw1nc3k.

Right now my solution is to have a metadata file with the player names in it and filter anything not in that list, but it's not ideal.

**Comment by LaihoE** [comment]
Thanks for the issue, this definitely needs to be fixed. The problem is actually in the parse_ticks and not exactly in the parse_events. I've been working on a bigger refactor and so ill fix it after. Here are 2 "glue" solutions in the meanwhile.

1. https://github.com/LaihoE/Python-demoparser/issues/7 Look at this issue we discussed team_num var it should work for filtering the players.
2. If you are only interested in the player and the victim you can do this (it will add columns like: player_X and victim_X):     
```python 
parser = DemoParser(file)
df = pd.DataFrame(parser.parse_events('player_death', props=['X', 'Y', 'Z']))
df.to_csv(output_path, index=False)
```

**Comment by AryanAb** [comment]
Thanks for your solutions. The first solution you provided actually does what I need. Made the code much simpler and cleaner.
