### ISSUE TITLE
use the rust parser without python bindings?

### ISSUE THREAD

**Issue by willjsaint** [LaihoE/Python-demoparser#3]
is there any way to utilize the rust parser natively within rust? i’m looking to learn rust and this seems like the only other rust demo parser i’ve found that’s not 5 years out of date. i realize it would be more difficult than just using the python bindings however im doing it specifically to try and teach myself some more rust

**Comment by LaihoE** [comment]
Unfortunately there is currently no good way to use it directly from Rust. I'll keep it in mind. It's also not so clear to me what the best interface would look like. Should it be similar to the python one, using Polars, or should it be like the other parsers with hooks that return the internal objects? What do you think would be a preferable interface?

Also as someone who has recently learned Rust I would recommend to go REAL easy in the beginning no matter how experienced you are. The language has a close to vertical learning curve in the beginning.

**Comment by willjsaint** [comment]
I’ll keep that in mind for sure. It definitely seems a lot different than the C# and TypeScript i’m used to!

I’ve only used the other ones that return the engine objects so that’s what I’m personally used to and probably what I’d prefer to work with, however I’ll try giving this one a shot and compare. For general usability though I imagine having it more similar to the other options available would be better as it would make it easier to use if someone already had experience with another parser. 

Realistically I just need a parser more performant than demofile and I’m not really a fan of go and demoinfo so I’ll give this one a try. I need to brush up on python anyway so this gives me another good excuse to practice a new language

**Comment by willjsaint** [comment]
Good lord this one is many thousands of times faster than even DemoInfoCS. thats absolutely wild just watching it instantly parse it.

**Comment by LaihoE** [comment]
There are some plans to add a rust crate for the source 2 version but at least not this one. Also the output will mimic the one python has. Sorry.
