### ISSUE TITLE
Is it possible to get stats like ADR, MVPs, and other scoreboard items?

### ISSUE THREAD

**Issue by DandrewsDev** [LaihoE/Python-demoparser#4]
I've looked through the examples and readme, didn't see any mention for querying those sort of built stats. 
My guess is that these are not available directly, but could be aggregated through a series of events. Like ADR, listening to an event for a player being damaged, getting the attacker info, getting the dmg delt, adding up total dmg for each player, and then at the end / by total rounds. 
But I wanted to see if there was some pre-built method for extracting data like that.

**Comment by LaihoE** [comment]
Added an example for this. Please update the version since I added "round" as a possible var.

In case you missed it, there is a file named vars.md in the root of the project showing possible properties.

**Comment by DandrewsDev** [comment]
Awesome, thanks for adding this. Also thank you for pointing out the vars.md file. Both were super helpful here.
