### ISSUE TITLE
Get players current team as part of "player_death" event. 

### ISSUE THREAD

**Issue by DandrewsDev** [LaihoE/Python-demoparser#7]
I am looking to get the players team on the player_death event. Ideally I'd like to get both the victim and attackers teams as part of the event. 

I tried using the parse_players, to get their starting teams and then swap those based on round for 2nd half and swaps during overtime. However the Faceit demos Im using don't seem to have consistently good data when doing that player parse. I often see matches 6v4, or teams that are just incorrect.

**Comment by LaihoE** [comment]
Thanks for issue, parse_players seems to have a bug when players are disconnecting during the game. Luckily for you I think there already is a prop for what you are looking for. Its called team_num and it can be 3 different values. 
1 = spectator
2 = terrorist
3 = CT 

(or the other way around if I remember CT and T wrong). You could use it like so:

```python
data = parser.parse_events("player_death", props=["team_num"])
```

**Comment by DandrewsDev** [comment]
Perfect! 
Was able to add that prop and get back the team numbers for both attacker an victim. Thank you!
