### ISSUE TITLE
No ARM/macOS build for latest version

### ISSUE THREAD

**Issue by arrivance** [LaihoE/Python-demoparser#8]
Hi, cheers for this project!

I think I've ran into a variant of #5 and #6, where trying to install this on an ARM Mac machine only retrieves 0.1.0, as the latest build wasn't compiled for ARM (or at least, the CI workflow only targets x86_64).

It looks as if GitHub haven't got GitHub hosted runners for Mac/ARM (https://github.com/actions/runner/issues/805#issuecomment-1438149537), so this might be too out of scope for at least the CI workflow.

Example of trying to force install 0.3.3:
```
(venv) bevan@Bevans-Air demo-parsing % pip install demoparser==0.3.3
ERROR: Could not find a version that satisfies the requirement demoparser==0.3.3 (from versions: 0.1.0)
ERROR: No matching distribution found for demoparser==0.3.3
```

(runtime error due to lack of feature as it's outdated
```
(venv) bevan@Bevans-Air demo-parsing % python dparser.py
Traceback (most recent call last):
  File "/Users/bevan/Documents/demo-parsing/dparser.py", line 5, in <module>
    events = parser.parse_events("round_end", props=["health"])
TypeError: DemoParser.parse_events() got an unexpected keyword argument 'props'
```
)

**Comment by LaihoE** [comment]
Thanks for the issue. Yeah the 0.1.0 was probably me just testing around with the CI and not an actual release. I can revisit the CI after im done with a bigger feature for the parser. If you want to try building it from source then it should go something like this:

install before:
the rust compiler ie. https://www.rust-lang.org/tools/install
pip install maturin

Then it should just be this:
```
git clone https://github.com/LaihoE/Python-demoparser.git
cd Python-demoparser/
maturin develop --release
```
If everything goes smoothly then it should install it to your current env.
