### ISSUE TITLE
Slice out of range issue. Small percent of faceit demos.

### ISSUE THREAD

**Issue by DandrewsDev** [LaihoE/Python-demoparser#9]
Hey, noticed a couple of these issues with some recent demos I was parsing. Using the most recent code built from source, also tried using pre-built 0.3.3.

thread '<unnamed>' panicked at 'range end index 119537713 out of range for slice of length 119537664', src/parsing/read_bytes.rs:46:36

Heres a link to a demo that Im seeing throw this error on parse.
https://demos-us-central1.faceit-cdn.net/csgo/1-5fde3080-1c4f-4871-b6a6-a63e6edb9523-1-1.dem.gz

I tried it a few times, it consistently happens for a select handful of demos, but works for the vast majority of faceit demos Im parsing.

**Comment by LaihoE** [comment]
hmm, interesting. I downloaded the demo and it worked fine. Could you try to re-download the demo? The error just says that "demo ended early". This could happen if the download wasn't completed fully. Anyhow there should be some way to handle this. What do you think? Should it just give a warning and return the data it was able to get?

**Comment by DandrewsDev** [comment]
Okay so after a while of debugging I found the issue was due to an issue and minor inconstancy in how I was un-gzipping the demo file automatically. I've since fixed the issue.

As for handling an error like this, some ability to catch that error, and get a message like "demo ended early" would be great.

**Comment by LaihoE** [comment]
This should not be a problem with CS2 version as proper errors are returned.
